### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [AkanshaJajodia/TipCalculator#1]
Thanks for submitting your pre-work, but your current submission is incomplete. Your GIF does not render on our end and the README appears incomplete (no required stories outlined as part of the prework). Make sure you've committed all your changes and have pushed them to GitHub. 

Please review the [prework submission checklist](https://courses.codepath.org/snippets/ios_university/prework.md#heading-submission-checklist) to complete the missing features. Please re-submit your project on your [application dashboard](https://apply.codepath.org/dashboard/), and it will notify us to review again.

**Comment by AkanshaJajodia** [comment]
Hi Team,

I am not able to update the application on the portal.

Here is the updated GIF: http://g.recordit.co/BhKpVX7s24.gif
Link to Github: https://github.com/AkanshaJajodia/TipCalculator

Thanks and Regards,
Akansha Jajodia
